### ISSUE TITLE
workerpool 希望能扩展多个job同时运行全部结束退出

### ISSUE THREAD

**Issue by dmskys** [mix-go/workerpool#2]
现在的workerpool只支持单个job运行结束
但是我想一个命令行程序内支持多个job队列，并且我发送退出信号时希望每个job都结束才结束进程
现在这个只能支持单个job任务，如果有多个job，那需要写多个控制台程序，就变成了多进程了

**Comment by onanying** [comment]
@dmskys 同一个进程可以开启任意各 workerpool ，用 go func 启动一个新协程在里面做 workerpool 逻辑即可，也就是说你的这个需求本来就可以实现，但是需要你自己处理信号监听去停止这些 N 各 pool

**Comment by onanying** [comment]
这样吧，我教一下你怎么搞，这个不属于库封装的范围，你可以把全部的 pool 都在  go func 子协程启动, 在 main 函数里，用 WaitGroup 来等待这些协程的结束，然后 sig 信号的时候， stop 这些 pool 即可，当全部 pool 退出， wg 就退出了，这样就做到平滑停止全部的 pool 了。

**Comment by dmskys** [comment]
嗯 后来想了一下 也是你这个这个想法
